// presentation/src/components/Select.vue
<template>
  <div>
    <Select
      :model-value="value"
      @update:model-value="handleValueUpdate"
      :disabled="disabled"
      :open="open"
      @update:open="handleOpenUpdate"
    >
      <SelectTrigger
        :class="[
          'bg-background border-border h-8 w-full select-none rounded border pr-8 transition-colors duration-200',
          'hover:border-primary focus:border-primary focus:outline-none',
          disabled ? 'cursor-default border-gray-300 bg-gray-50 text-gray-400' : 'cursor-pointer',
          hasCustomIcon ? 'has-custom-icon' : '',
        ]"
      >
        <SelectValue :placeholder="placeholder">
          <template v-if="showLabel">{{ showLabel }}</template>
        </SelectValue>
        <div
          v-if="hasCustomIcon"
          class="text-muted-foreground pointer-events-none absolute right-0 top-0 flex h-7 w-8 items-center justify-center"
        >
          <slot name="icon">
            <IconDown :size="14" />
          </slot>
        </div>
      </SelectTrigger>
      <SelectContent class="max-h-64 select-none">
        <template v-if="search">
          <div class="mb-1.5 border-b border-gray-200 p-1.5">
            <Input
              ref="searchInputRef"
              simple
              :placeholder="searchPlaceholder"
              v-model:value="searchKey"
              class="w-full"
            />
          </div>
        </template>
        <template v-for="option in showOptions" :key="option.value">
          <SelectItem
            :value="option.value"
            :disabled="option.disabled"
            :class="[
              'focus:text-primary h-8 truncate rounded border-none px-1.5 leading-8 focus:font-bold focus:outline-none',
              option.disabled ? 'text-gray-400' : 'hover:bg-primary/5 focus:bg-primary/5 cursor-pointer',
              option.value === value ? 'text-primary focus:text-accent font-bold' : '',
            ]"
          >
            {{ option.label }}
          </SelectItem>
        </template>
      </SelectContent>
    </Select>
  </div>
</template>

<script lang="ts" setup>
import { computed, ref, watch, nextTick, onBeforeUnmount, useSlots } from 'vue';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import Input from './Input.vue';
import { useI18n } from 'vue-i18n';

const { t } = useI18n();

interface SelectOption {
  label: string;
  value: string | number;
  disabled?: boolean;
}

const props = withDefaults(
  defineProps<{
    value: string | number;
    options: SelectOption[];
    disabled?: boolean;
    search?: boolean;
    searchLabel?: string;
    placeholder?: string;
  }>(),
  {
    disabled: false,
    search: false,
    searchLabel: '',
    placeholder: '',
  }
);

const emit = defineEmits<{
  (event: 'update:value', payload: string | number): void;
}>();

const open = ref(false);
const searchInputRef = ref<InstanceType<typeof Input>>();
const searchKey = ref('');

// Check if custom icon slot is being used
const slots = useSlots();
const hasCustomIcon = computed(() => !!slots.icon);

const showLabel = computed(() => {
  return props.options.find((item) => item.value === props.value)?.label || props.value;
});

const searchPlaceholder = computed(() => {
  return props.searchLabel || t('ui.components.select.search');
});

const showOptions = computed(() => {
  if (!props.search) return props.options;
  if (!searchKey.value.trim()) return props.options;
  const opts = props.options.filter((item) => {
    return item.label.toLowerCase().indexOf(searchKey.value.toLowerCase()) !== -1;
  });
  return opts.length ? opts : props.options;
});

const handleValueUpdate = (newValue: any) => {
  if (newValue !== null && newValue !== undefined) {
    // Convert bigint to string to maintain compatibility, handle any type
    let value = newValue;
    if (typeof newValue === 'bigint') {
      value = newValue.toString();
    } else if (typeof newValue === 'object') {
      // For complex objects, try to extract a value property or convert to string
      value = newValue.value || JSON.stringify(newValue);
    }
    emit('update:value', value);
  }
};

const handleOpenUpdate = (isOpen: boolean) => {
  open.value = isOpen;
  if (isOpen) {
    nextTick(() => {
      if (searchInputRef.value) searchInputRef.value.focus();
    });
  } else {
    searchKey.value = '';
  }
};

onBeforeUnmount(() => {
  searchKey.value = '';
});
</script>

<style lang="scss" scoped>
:deep(.has-custom-icon [data-slot='select-icon']) {
  display: none;
}

:deep([data-slot='select-value']) {
  min-width: 50px;
  height: 30px;
  line-height: 30px;
  padding-left: 10px;
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
  justify-content: flex-start;
}
</style>

// admin/src/components/ui/select.tsx
import * as React from 'react';
import * as SelectPrimitive from '@radix-ui/react-select';
import { Check, ChevronDown, ChevronUp } from 'lucide-react';
import { cn } from '@/lib/utils';

const Select = SelectPrimitive.Root;

const SelectGroup = SelectPrimitive.Group;

const SelectValue = SelectPrimitive.Value;

const SelectTrigger = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Trigger>
>(({ className, children, ...props }, ref) => (
  <SelectPrimitive.Trigger
    ref={ref}
    className={cn(
      'border-input ring-offset-background placeholder:text-muted-foreground focus:ring-ring flex h-9 w-full items-center justify-between whitespace-nowrap rounded-md border bg-transparent px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-1 disabled:cursor-not-allowed disabled:opacity-50 [&>span]:line-clamp-1',
      className
    )}
    {...props}
  >
    {children}
    <SelectPrimitive.Icon asChild>
      <ChevronDown className="h-4 w-4 opacity-50" />
    </SelectPrimitive.Icon>
  </SelectPrimitive.Trigger>
));
SelectTrigger.displayName = SelectPrimitive.Trigger.displayName;

const SelectScrollUpButton = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.ScrollUpButton>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.ScrollUpButton>
>(({ className, ...props }, ref) => (
  <SelectPrimitive.ScrollUpButton
    ref={ref}
    className={cn('flex cursor-default items-center justify-center py-1', className)}
    {...props}
  >
    <ChevronUp className="h-4 w-4" />
  </SelectPrimitive.ScrollUpButton>
));
SelectScrollUpButton.displayName = SelectPrimitive.ScrollUpButton.displayName;

const SelectScrollDownButton = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.ScrollDownButton>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.ScrollDownButton>
>(({ className, ...props }, ref) => (
  <SelectPrimitive.ScrollDownButton
    ref={ref}
    className={cn('flex cursor-default items-center justify-center py-1', className)}
    {...props}
  >
    <ChevronDown className="h-4 w-4" />
  </SelectPrimitive.ScrollDownButton>
));
SelectScrollDownButton.displayName = SelectPrimitive.ScrollDownButton.displayName;

const SelectContent = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Content>
>(({ className, children, position = 'popper', ...props }, ref) => (
  <SelectPrimitive.Portal>
    <SelectPrimitive.Content
      ref={ref}
      className={cn(
        'bg-popover text-popover-foreground data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 relative z-50 max-h-96 min-w-[8rem] overflow-hidden rounded-md border shadow-md',
        position === 'popper' &&
          'data-[side=bottom]:translate-y-1 data-[side=left]:-translate-x-1 data-[side=right]:translate-x-1 data-[side=top]:-translate-y-1',
        className
      )}
      position={position}
      {...props}
    >
      <SelectScrollUpButton />
      <SelectPrimitive.Viewport
        className={cn(
          'p-1',
          position === 'popper' &&
            'h-[var(--radix-select-trigger-height)] w-full min-w-[var(--radix-select-trigger-width)]'
        )}
      >
        {children}
      </SelectPrimitive.Viewport>
      <SelectScrollDownButton />
    </SelectPrimitive.Content>
  </SelectPrimitive.Portal>
));
SelectContent.displayName = SelectPrimitive.Content.displayName;

const SelectLabel = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Label>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Label>
>(({ className, ...props }, ref) => (
  <SelectPrimitive.Label
    ref={ref}
    className={cn('px-2 py-1.5 text-sm font-semibold', className)}
    {...props}
  />
));
SelectLabel.displayName = SelectPrimitive.Label.displayName;

const SelectItem = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Item>
>(({ className, children, ...props }, ref) => (
  <SelectPrimitive.Item
    ref={ref}
    className={cn(
      'focus:bg-accent focus:text-accent-foreground relative flex w-full cursor-default select-none items-center rounded-sm py-1.5 pl-2 pr-8 text-sm outline-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
      className
    )}
    {...props}
  >
    <span className="absolute right-2 flex h-3.5 w-3.5 items-center justify-center">
      <SelectPrimitive.ItemIndicator>
        <Check className="h-4 w-4" />
      </SelectPrimitive.ItemIndicator>
    </span>
    <SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText>
  </SelectPrimitive.Item>
));
SelectItem.displayName = SelectPrimitive.Item.displayName;

const SelectSeparator = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Separator>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Separator>
>(({ className, ...props }, ref) => (
  <SelectPrimitive.Separator ref={ref} className={cn('bg-muted -mx-1 my-1 h-px', className)} {...props} />
));
SelectSeparator.displayName = SelectPrimitive.Separator.displayName;

export {
  Select,
  SelectGroup,
  SelectValue,
  SelectTrigger,
  SelectContent,
  SelectLabel,
  SelectItem,
  SelectSeparator,
  SelectScrollUpButton,
  SelectScrollDownButton,
};
